# Sélecteurs HTML pour le concours "GULLI - Jackpot Jurassic World" (Instant Gagnant)
# Domaine : grattweb.fr
# Objectif : préremplir et soumettre automatiquement le formulaire

form:
  url: "https://www.grattweb.fr/instant-gagnant/gulli-jackpot-jurassic-world"
  method: "post"

selectors:
  lastname: "input[name='lastname']"
  firstname: "input[name='firstname']"
  email: "input[name='email']"
  terms: "input[name='terms']"          # case CGU obligatoire
  newsletter: "input[name='newsletter']" # case optionnelle
  submit: "button[type='submit']"

confirmation:
  success_text: "Votre participation a bien été enregistrée"
  selector: ".alert-success"

meta:
  type: "instant_gagnant"
  theme: "jouets_enfants"
  recurrence: "quotidienne"
  site: "grattweb.fr"
  status: "actif"
