# Sélecteurs HTML pour le concours "GULLI - Jackpot Jurassic World" (Instant Gagnant)
# Domaine : grattweb.fr

form:
  url: "https://www.grattweb.fr/gulli-jeu-jackpot-jurassic-world/product_info.php/products_id/63479"
  method: "post"

selectors:
  lastname: "input[name='lastname']"
  firstname: "input[name='firstname']"
  email: "input[name='email']"
  terms: "input[name='terms']"           # case CGU obligatoire (si présente)
  newsletter: "input[name='newsletter']" # optionnelle (si présente)
  submit: "button[type='submit'], input[type='submit']"

confirmation:
  success_text: "Votre participation a bien été enregistrée"
  selector: ".alert-success, .messageStackSuccess"

meta:
  type: "instant_gagnant"
  theme: "jouets_enfants"
  recurrence: "quotidienne"
  site: "grattweb.fr"
  status: "actif"
